### ISSUE TITLE
bad indentation with cdata

### ISSUE THREAD

**Issue by ne555** [leforestier/yattag#73]
```python
from yattag import Doc, indent


doc, tag, text = Doc().tagtext()
with tag('div'):
    with tag('item'):
        doc.cdata('6*9')
    with tag('item'):
        doc.cdata('42')

result = indent(
    doc.getvalue(),
    indentation = ' '*2,
)
print(result)
```
produces the output
```
<div>
  <item>
    <![CDATA[6*9]]></item><item><![CDATA[42]]>
  </item>
</div>
```
expected
```
<div>
  <item><![CDATA[6*9]]></item>
  <item><![CDATA[42]]></item>
</div>
```

**Comment by brainysmurf** [comment]
Also seeing this issue.

**Comment by leforestier** [comment]
Hello,
thanks for bringing up that issue and sorry for not replying earlier. I lack the time to look into this at the moment.
I think I had added  the CDATA handling after the rest and had probably overlooked that case in the indent function. I think if such CDATA nodes were treated in the same way as text nodes are treated, it should work as expected.
I will accept a pull request if you find a fix. Otherwise I will try to look into it when I have some time.

**Comment by ne555** [comment]
```diff --git a/yattag/indentation.py b/yattag/indentation.py
index 74ac5bd..fadd0af 100644
--- a/yattag/indentation.py
+++ b/yattag/indentation.py
@@ -58,7 +58,7 @@ class Comment(Token):
     regex = r'<!--((?!-->).)*.?-->'
 
 class CData(Token):
-    regex = r'<!\[CDATA\[((?!\]\]>).*).?\]\]>'
+    regex = r'<!\[CDATA\[(.*?)\]\]>'
 
 class Doctype(Token):
     regex = r'''<!DOCTYPE(\s+([^<>"']+|"[^"]*"|'[^']*'))*>'''
```

just making the regex lazy till it find the closing ]]>
dunno if regex is the proper way

**Comment by leforestier** [comment]
Hi, thanks for your  contribution. Does your change fixes the issue with the indentation?
I will try to write some tests when I have some time.

**Comment by ne555** [comment]
yes, it fixes it.
when debugging the code noticed that the tokenizer gave only one CData token, with `6*9]]></item><item><![CDATA[42` as value, so modified the regex to stop at the first `]]>` occurrence

**Comment by leforestier** [comment]
Excellent! Thank you for looking into it and finding a fix.
Do you want to submit a pull request with that change? It would be nice to add a test case about CDATA in test_indentation.py.
If you want to do it, I will gladly accept your pull request. 
Otherwise I will add your changes to the code myself in a few days.
Thanks again for your contribution.

**Comment by leforestier** [comment]
I added your fix. Thanks again for your contribution.
The new version is now available on pypi and can be downloaded/upgraded with pip.
